version: '3.3'
services:
  jenkins:
    build: "./jenkins/."
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs