jenkins:
  systemMessage: "I did this using Jenkins Configuration as Code Plugin \n\n"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'JenkinsFile_Hello'
                  scm {
                    git {
                        remote { url 'https://github.com/slastrina/jenkins_script.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }